# Generated by Django 5.2.6 on 2025-09-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('dificulty', models.IntegerField(default=1)),
                ('isVegan', models.BooleanField(default=False)),
                ('ingredients', models.TextField()),
                ('servings', models.IntegerField(default=1)),
                ('prepareTime', models.IntegerField(default=1)),
                ('prepareSteps', models.TextField()),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
            },
        ),
    ]
