# Generated by Django 5.2.6 on 2025-09-18 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_remove_recipe_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('sector', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=30)),
                ('criticality', models.IntegerField()),
                ('criticalityColor', models.CharField(blank=True, max_length=30)),
                ('priority', models.IntegerField()),
                ('description', models.TextField()),
                ('closeDesc', models.TextField()),
                ('finalStatus', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'verbose_name': 'Chamado',
                'verbose_name_plural': 'Chamados',
            },
        ),
    ]
