# Generated by Django 5.2.6 on 2025-09-19 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.sector'),
        ),
    ]
