# Generated by Django 5.2.6 on 2026-02-10 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0006_alter_ticket_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('saleValue', models.BigIntegerField(default=0)),
                ('saleDate', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.sector'),
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=10)),
                ('photo', models.CharField(max_length=100)),
                ('creci', models.CharField(max_length=7)),
                ('email', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=12)),
                ('sales', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.sales')),
            ],
        ),
    ]
