# Generated by Django 5.2.6 on 2026-02-10 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0007_sales_alter_ticket_sector_broker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.sales'),
        ),
    ]
