# Generated by Django 5.2.6 on 2026-02-10 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0008_alter_broker_sales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broker',
            options={'verbose_name': 'Corretor', 'verbose_name_plural': 'Corretores'},
        ),
        migrations.RemoveField(
            model_name='broker',
            name='sales',
        ),
    ]
