# Generated by Django 5.2.6 on 2026-02-10 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0009_alter_broker_options_remove_broker_sales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broker',
            options={'verbose_name': 'Corretores'},
        ),
        migrations.AddField(
            model_name='broker',
            name='sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.sales'),
        ),
    ]
