# Generated by Django 5.2.6 on 2026-02-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0010_alter_broker_options_broker_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='sales',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
